name: fragment_shader_example
description: A simple example of a custom shader in a Flutter app
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0-147.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  shaders:
    - shaders/inkwell.frag
    - shaders/sampler.frag
    - shaders/solid_color.frag
    - shaders/blank.frag
    - shaders/example.frag
    - shaders/clouds.frag
    - shaders/oceanwaves.frag
    - shaders/star_nest.frag
    - packages/flutter_shaders/shaders/pixelation.frag
